import "./video-review.js";
/* Site configuration */
export const SITE = {
  name: "Harshal Chouhan",
  nameShort: "HC",
  email: "harshalchouhan723@gmail.com",
  phone: "7746821965",
  linkedin: "https://www.linkedin.com/in/harshal-chouhan-17b5ba247",
  instagram: "https://instagram.com",
  resumePath: "assets/resume.pdf",
  profileImagePath: "assets/profile.jpg",
  bikeModelPath: "assets/bike.glb",
};

export const PROJECTS = [
  { title: "Client & Account Management", category: "Business", image: "assets/projects/project-01.jpg", description: "Managing client relationships, briefs, communication, feedback and delivery across projects.", role: "Key Account Manager", contribution: "Client communication, requirement understanding, follow-ups and relationship management.", tools: "Client Management · Coordination · Communication", link: "", video: "" },
  { title: "Project Coordination", category: "Projects", image: "assets/projects/project-02.jpg", description: "Keeping teams, timelines, revisions and deliverables aligned from brief to final delivery.", role: "Project Coordinator", contribution: "Planning, team coordination, deadline tracking, quality checks and final delivery.", tools: "Planning · Workflow · Quality Control", link: "", video: "" },
  { title: "Creative Collaboration", category: "Creative", image: "assets/projects/project-03.jpg", description: "Contributing ideas, scripts, content direction and creative references to projects.", role: "Creative Collaborator", contribution: "Ideation, content suggestions, script improvements and visual references.", tools: "Creative Ideation · Content · AI Tools", link: "", video: "" },
  { title: "Content & Production", category: "Production", image: "assets/projects/project-04.jpg", description: "Coordinating production workflows, shoots, editing, reviews and final deliverables.", role: "Production Coordinator", contribution: "Shoot coordination, script coordination, editing workflow and final checks.", tools: "Production · Video · Review", link: "", video: "" },
  { title: "Sales Leadership", category: "Leadership", image: "assets/projects/project-05.jpg", description: "Leading a 6+ member sales team while managing customers, targets and coordination.", role: "Team Leader – Sales", contribution: "Team management, customer interaction, sales coordination and performance support.", tools: "Leadership · Sales · Team Management", link: "", video: "" },
];

/* Premium contact CTAs: this runs from the already-imported config module, so no other page logic is changed. */
if (typeof document !== "undefined") {
  const installContactStyle = () => {
    if (document.getElementById("premium-contact-cta-style")) return;
    const style = document.createElement("style"); style.id = "premium-contact-cta-style"; style.textContent = `.contact-glass-cta{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;min-width:132px!important;padding:12px 16px!important;border:1px solid rgba(255,255,255,.12)!important;border-radius:16px!important;background:linear-gradient(145deg,rgba(255,255,255,.085),rgba(255,255,255,.025))!important;color:#fff!important;text-decoration:none!important;box-shadow:0 14px 40px rgba(0,0,0,.38),inset 0 1px 0 rgba(255,255,255,.08)!important;backdrop-filter:blur(15px)!important;-webkit-backdrop-filter:blur(15px)!important;transition:transform .3s ease,border-color .3s ease,box-shadow .3s ease!important;font-size:13px!important;font-weight:700!important}.contact-glass-cta:hover{transform:translateY(-4px)!important;border-color:rgba(255,255,255,.28)!important}.contact-glass-cta .cta-icon{width:32px;height:32px;display:grid;place-items:center;border-radius:10px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1);flex:0 0 32px}.contact-glass-cta .cta-icon svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.cta-linkedin .cta-icon{color:#78b8ff}.cta-whatsapp .cta-icon{color:#63e99a}.cta-email .cta-icon{color:#ff9bc5}.cta-phone .cta-icon{color:#c9b7ff}.contact-glass-cta .cta-label{white-space:nowrap}@media(max-width:600px){.contact-glass-cta{min-width:0!important;padding:10px 12px!important}.contact-glass-cta .cta-icon{width:30px;height:30px;flex-basis:30px}.contact-glass-cta .cta-label{font-size:12px}}#whatsapp-float{display:none!important}`; document.head.appendChild(style);
  };
  const enhance = () => { installContactStyle(); const icons={phone:'<svg viewBox="0 0 24 24"><path d="M7.2 4.2 9.1 3.5c.6-.2 1.2.1 1.4.7l1 2.4c.2.5.1 1-.3 1.3L9.9 9c.9 1.9 2.4 3.4 4.3 4.3l1.1-1.4c.3-.4.8-.5 1.3-.3l2.4 1c.6.2.9.8.7 1.4l-.7 1.9c-.2.6-.8.9-1.4.9-6.2-.1-10.9-4.8-11-11 0-.6.3-1.2.9-1.6Z"/></svg>',mail:'<svg viewBox="0 0 24 24"><path d="M3.5 5.5h17v13h-17zM4 6l8 6 8-6"/></svg>',linkedin:'<svg viewBox="0 0 24 24"><path d="M5 8a1.7 1.7 0 1 0 0-3.4A1.7 1.7 0 0 0 5 8ZM3.5 9.5h3v10h-3zM9 9.5h2.9V11h.1c.4-.8 1.4-1.8 3.2-1.8 3.4 0 4 2.2 4 5v5.3H16v-4.7c0-1.1 0-2.5-1.6-2.5s-1.8 1.2-1.8 2.5v4.7H9z"/></svg>',whatsapp:'<svg viewBox="0 0 24 24"><path d="M20 4a9.8 9.8 0 0 0-15.5 11.7L3.2 20.8l5.2-1.3A9.8 9.8 0 1 0 20 4Zm-8 15a8 8 0 0 1-4-1.1l-.3-.2-3 .8.8-2.9-.2-.3A8 8 0 1 1 12 19Zm4.4-5.8c-.2-.1-1.3-.6-1.5-.7-.2-.1-.4-.1-.5.1l-.7.8c-.1.2-.3.2-.5.1a6.4 6.4 0 0 1-1.8-1.1 6.8 6.8 0 0 1-1.2-1.5c-.1-.2 0-.3.1-.4l.4-.5c.1-.1.1-.3.1-.4l-.7-1.6c-.2-.4-.3-.4-.5-.4h-.4c-.2 0-.4.1-.6.3-.2.2-.7.8-.7 1.8s.7 2.1.8 2.2c.1.2 1.5 2.4 3.7 3.4 2.2 1 2.2.7 2.6.7.4 0 1.3-.5 1.5-1 .2-.5.2-.9.1-1Z"/></svg>'}; [['[data-bind="email-link"]','Email Me','mail'],['[data-bind="linkedin-link"]','Connect','linkedin'],['[data-bind="whatsapp-link"]','Chat Now','whatsapp'],['a[href^="tel:"]','Call Me','phone']].forEach(([selector,label,icon])=>document.querySelectorAll(selector).forEach(el=>{if(el.id==='whatsapp-float')return;el.classList.add('contact-glass-cta','cta-'+icon);el.innerHTML='<span class="cta-icon">'+icons[icon]+'</span><span class="cta-label">'+label+'</span>';el.setAttribute('aria-label',label);if(icon==='linkedin'||icon==='whatsapp'){el.target='_blank';el.rel='noopener noreferrer'}}));}; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance(); }
