(()=>{'use strict';
const css=document.createElement('link');css.rel='stylesheet';css.href='css/video-review.css';document.head.appendChild(css);
const section=`<section class="section" id="video-review"><div class="container"><p class="eyebrow reveal">Smart QC Tool</p><h2 class="section-title reveal">VIDEO TEXT REVIEW</h2><p class="section-sub reveal">Context-aware spelling & punctuation review for on-screen text.</p><div id="video-review-tool"><div class="vr-modes"><button class="vr-mode" data-mode="spelling">Spelling</button><button class="vr-mode" data-mode="punctuation">Punctuation</button><button class="vr-mode active" data-mode="both">Both</button></div><div class="vr-inputs"><label class="vr-drop"><input id="vr-file" type="file" accept="video/mp4,video/*"><span><strong>Drop MP4 here</strong><br><small>or click to choose</small></span></label><div class="vr-drive-wrap"><strong>Google Drive</strong><input class="vr-drive" id="vr-drive" type="url" placeholder="Paste Google Drive share link"><small>Use Anyone with the link → Viewer.</small></div><div class="vr-drive-wrap"><strong>Frame.io</strong><input class="vr-frameio" id="vr-frameio" type="url" placeholder="Paste Frame.io share link"><small>Public/shareable Frame.io links only.</small></div></div><label class="vr-script"><strong>Optional script</strong><small>Paste the voiceover/script here. It is used as context — not as a blind replacement list.</small><textarea id="vr-script-text" rows="6" placeholder="Paste video script / voiceover here..."></textarea></label><div class="vr-source" id="vr-source-name">No video selected</div><video id="vr-video" class="vr-video" controls playsinline hidden></video><div class="vr-actions"><button class="vr-btn primary" id="vr-start" disabled>Scan video</button><button class="vr-btn" id="vr-cancel">Cancel</button></div><div class="vr-status" id="vr-status">Ready</div><progress class="vr-progress" id="vr-progress" max="100" value="0"></progress><div class="vr-results" id="vr-results"></div></div></div></section>`;
function mount(){if(document.getElementById('video-review'))return;const contact=document.getElementById('contact');if(!contact)return;contact.insertAdjacentHTML('beforebegin',section);document.querySelectorAll('.nav-links,.mobile-menu').forEach(n=>{if(!n.querySelector('a[href="#video-review"]')){const a=document.createElement('a');a.href='#video-review';a.textContent='Tools';n.insertBefore(a,n.querySelector('a[href="#contact"]')||null)}});init()}
const $=id=>document.getElementById(id),S={mode:'both',cancel:false,scheduler:null,workers:[],words:null,wordBuckets:new Map(),cache:new Map(),script:[]};
const fixes={teh:'the',recieve:'receive',seperate:'separate',definately:'definitely',occured:'occurred',accomodate:'accommodate',enviroment:'environment',goverment:'government',untill:'until',tommorow:'tomorrow',succesful:'successful',adress:'address',becuase:'because',wierd:'weird',experiance:'experience',developement:'development',managment:'management',calender:'calendar',priviledge:'privilege',begining:'beginning',maintanance:'maintenance',recomend:'recommend',acommodate:'accommodate',arguement:'argument',comming:'coming',definate:'definite',occassion:'occasion',persue:'pursue',wich:'which',whitch:'which',thier:'their',reciever:'receiver',beleive:'believe',lable:'label',sucess:'success',sucessful:'successful',responsibilty:'responsibility',availble:'available',finaly:'finally',immediatly:'immediately',independant:'independent',acheive:'achieve',acheived:'achieved',concious:'conscious',consistant:'consistent',conveniant:'convenient',embarass:'embarrass',existance:'existence',foriegn:'foreign',greatful:'grateful',guarentee:'guarantee',heigth:'height',liason:'liaison',neccessary:'necessary',noticable:'noticeable',occurence:'occurrence',prefered:'preferred',pronounciation:'pronunciation',publically:'publicly',realy:'really',refered:'referred',suprise:'surprise',truely:'truly',writting:'writing',alot:'a lot',thru:'through',reciept:'receipt',sucessesful:'successful'};
const contractions={dont:"don't",cant:"can't",wont:"won't",isnt:"isn't",arent:"aren't",wasnt:"wasn't",werent:"weren't",didnt:"didn't",doesnt:"doesn't",couldnt:"couldn't",wouldnt:"wouldn't",shouldnt:"shouldn't",youre:"you're",theyre:"they're",ive:"I've",ill:"I'll",im:"I'm",lets:"let's"};
const clean=t=>String(t||'').replace(/\s+/g,' ').trim(),norm=w=>String(w||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z']/g,''),tokens=t=>(String(t||'').match(/[A-Za-z][A-Za-z'’-]*/g)||[]).map(norm).filter(Boolean),esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function tm(t){const m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor((t%1)*1000);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
function lev(a,b){if(Math.abs(a.length-b.length)>2)return 99;let p=Array(b.length+1);for(let j=0;j<=b.length;j++)p[j]=j;for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=q}return p[b.length]}
function noise(line,bottom=false){const x=clean(line),k=norm(x);if(!x||x.length<2)return true;if(/(?:https?:\/\/|www\.|\.com\b|\.in\b|@[\w.-]+|©|®|™)/i.test(x))return true;if(/\b(?:disclaimer|copyright|all rights reserved|terms and conditions|terms of use|privacy policy|legal notice|registration no|registered office|cin|gstin|pan no|iso\s*\d|warning)\b/i.test(x))return true;if(/\b(?:follow us|subscribe|like and share)\b/i.test(x)&&x.length<100)return true;if(/\b(?:\+?\d[\d\s().-]{7,}\d)\b/.test(x))return true;if(bottom&&x.length<120)return true;if(k.length<3)return true;return false}
function loadOCR(){return new Promise((ok,no)=>{if(window.Tesseract)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js';s.onload=ok;s.onerror=()=>no(Error('OCR engine could not load.'));document.head.appendChild(s)})}
async function dictionary(){if(S.words)return S.words;try{const r=await fetch('https://unpkg.com/wordlist-english@1.2.1/english-words-10.json',{cache:'force-cache'});const a=await r.json();S.words=new Set(a.map(x=>String(x).toLowerCase()));for(const x of S.words){if(x.length<4)continue;const key=x[0]+'|'+x.length;let b=S.wordBuckets.get(key);if(!b){b=[];S.wordBuckets.set(key,b)}b.push(x)}}catch{S.words=new Set(Object.keys(fixes));for(const x of S.words){const key=x[0]+'|'+x.length;let b=S.wordBuckets.get(key);if(!b){b=[];S.wordBuckets.set(key,b)}b.push(x)}}return S.words}
function scriptSetup(){S.script=tokens(clean($('vr-script-text').value))}
function bestScriptMatch(line){if(!S.script.length)return null;const a=tokens(line);if(a.length<2)return null;let best=null,bestScore=0;for(let i=0;i<S.script.length;i++){for(let len=Math.max(2,a.length-2);len<=Math.min(a.length+2,S.script.length-i);len++){const b=S.script.slice(i,i+len);let exact=0,near=0;for(let j=0;j<a.length;j++){let local=0;for(let q=0;q<b.length;q++){if(a[j]===b[q]){local=1;break}if(Math.abs(a[j].length-b[q].length)<=2&&lev(a[j],b[q])===1)local=.55}if(local===1)exact++;else if(local>.5)near+=local}const score=(exact+near*.35)/Math.max(a.length,b.length);if(score>bestScore){bestScore=score;best={a,b,score}}}}return best&&best.score>=.62?best:null}
function dictionaryFix(word){const k=norm(word);if(!k||k.length<4)return null;if(fixes[k])return fixes[k];if(!S.words||S.words.has(k)||S.cache.has(k))return S.cache.get(k)||null;let best=null,bd=99;for(const len of [k.length-1,k.length,k.length+1]){const bucket=S.wordBuckets.get(k[0]+'|'+len)||[];for(const x of bucket){const d=lev(k,x);if(d<bd){bd=d;best=x;if(d===1)break}}if(bd===1)break}const r=best&&bd===1?best:null;S.cache.set(k,r);return r}
function inspect(line){const out=[],ctx=bestScriptMatch(line);if(S.mode==='spelling'||S.mode==='both'){const raw=line.match(/\b[A-Za-z][A-Za-z'’-]*\b/g)||[];for(const w of raw){const k=norm(w);if(k.length<3)continue;let fix=null;if(ctx){let best=null,bd=99;for(const x of ctx.b){const d=lev(k,x);if(d<bd){bd=d;best=x}}const exactNeighbors=ctx.a.filter(x=>ctx.b.includes(x)).length;if(best&&best!==k&&bd===1&&exactNeighbors>=2)fix=best}if(!fix&&!S.script.length)fix=dictionaryFix(w);if(fix&&fix!==k)out.push({type:'Spelling',found:w,fix,context:!!ctx})}}
if(S.mode==='punctuation'||S.mode==='both'){let fixed=line.replace(/\s+([,.!?;:])/g,'$1').replace(/([,.!?;:])\1+/g,'$1');const cm=line.match(/\b(dont|cant|wont|isnt|arent|wasnt|werent|didnt|doesnt|couldnt|wouldnt|shouldnt|youre|theyre|ive|ill|im|lets)\b/i);if(cm)fixed=fixed.replace(cm[1],contractions[cm[1].toLowerCase()]||cm[1]);if(fixed!==line)out.push({type:'Punctuation',found:line,fix:fixed,context:!!ctx})}return out}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.length||!B.length)return 0;let hits=0;for(const x of A)if(B.some(y=>x===y))hits++;return hits/Math.min(A.length,B.length)}
function addObs(obs,t,data,h){const lines=(data.lines||[]).map(l=>({text:clean(l.text),conf:Number(l.confidence)||0,top:l.bbox?.y0||0,bottom:l.bbox?.y1||0}));for(const l of lines)if(l.conf>=52&&!noise(l.text,l.top>0&&h&&l.top>h*.86))obs.push({t,txt:l.text,cf:l.conf,top:l.top,bottom:l.bottom});if(!lines.length&&data.text&&Number(data.confidence)>=52&&!noise(data.text))obs.push({t,txt:clean(data.text),cf:Number(data.confidence),top:0,bottom:0})}
function seek(v,t){return new Promise((res,rej)=>{if(Math.abs(v.currentTime-t)<.04&&v.readyState>=2)return res();let done=false,to;const finish=()=>{if(done)return;done=true;clearTimeout(to);v.removeEventListener('seeked',finish);v.removeEventListener('timeupdate',check);res()};const check=()=>Math.abs(v.currentTime-t)<.12&&finish();v.addEventListener('seeked',finish);v.addEventListener('timeupdate',check);to=setTimeout(()=>Math.abs(v.currentTime-t)<.5?finish():rej(Error('Video seek timed out.')),6000);v.currentTime=t})}
async function createOCR(){await loadOCR();const scheduler=Tesseract.createScheduler(),workers=[],count=innerWidth<760?1:2;for(let i=0;i<count;i++){const w=await Tesseract.createWorker('eng',1,{langPath:'https://tessdata.projectnaptha.com/4.0.0_fast'});await w.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});scheduler.addWorker(w);workers.push(w)}S.scheduler=scheduler;S.workers=workers}
async function ocr(canvas){return(await S.scheduler.addJob('recognize',canvas)).data}
function stable(obs){obs.sort((a,b)=>a.t-b.t);const groups=[];for(const o of obs){let g=groups.find(x=>o.t-x.last<3.5&&similarity(o.txt,x.txt)>=.6);if(g){g.items.push(o);g.last=o.t}else groups.push({items:[o],last:o.t})}return groups.map(g=>g.items.slice().sort((a,b)=>b.cf-a.cf)[0]).filter(x=>x.cf>=52)}
function analyze(obs){const issues=[],seen=new Set();for(const o of stable(obs))for(const x of inspect(o.txt)){const key=`${x.type}|${norm(x.found)}|${norm(x.fix)}`;if(!seen.has(key)){seen.add(key);issues.push({...x,time:o.t})}}return issues.sort((a,b)=>a.time-b.time)}
function preprocess(src){const c=document.createElement('canvas'),ctx=c.getContext('2d');const max=1600,scale=Math.min(1,max/(src.width||max));c.width=Math.max(1,Math.round((src.width||1280)*scale));c.height=Math.max(1,Math.round((src.height||720)*scale));ctx.filter='contrast(1.08) saturate(.9)';ctx.drawImage(src,0,0,c.width,c.height);ctx.filter='none';return c}
async function scan(){const v=$('vr-video'),st=$('vr-status'),p=$('vr-progress'),box=$('vr-results');S.cancel=false;box.innerHTML='';scriptSetup();try{st.textContent=S.script.length?'Reading on-screen text + checking it against script context…':'Reading on-screen text…';await Promise.all([createOCR(),dictionary()]);if(!v.duration||!isFinite(v.duration))throw Error('Video duration could not be read.');const d=v.duration,mobile=innerWidth<760,step=d>180?(mobile?1.45:1.15):d>90?(mobile?1.15:.9):(mobile?.95:.72),n=Math.min(220,Math.max(18,Math.ceil(d/step))),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=Math.min(1600,v.videoWidth||1280);c.height=Math.round((v.videoHeight||720)*c.width/(v.videoWidth||1280));const obs=[];for(let i=0;i<n;i++){if(S.cancel)throw Error('Review cancelled.');const t=Math.min(d-.03,i*step);await seek(v,t);ctx.drawImage(v,0,0,c.width,c.height);let data=await ocr(c);data.h=c.height;if((Number(data.confidence)||0)<55||!(data.lines||[]).some(x=>Number(x.confidence)>=55)){const retry=await ocr(preprocess(c));if((Number(retry.confidence)||0)>(Number(data.confidence)||0))data=retry}addObs(obs,t,data,c.height);p.value=(i+1)/n*82;st.textContent=`Analyzing text ${i+1}/${n}…`}const issues=analyze(obs);p.value=100;box.innerHTML=`<div class="vr-results-head"><strong>${issues.length} verified issue${issues.length===1?'':'s'}</strong><button class="vr-copy-all" id="vr-copy-all" ${issues.length?'':'disabled'}>Copy all</button></div>`+(issues.length?issues.map(x=>`<article class="vr-issue"><div class="vr-issue-top"><span class="vr-type">${esc(x.type)}${x.context?' · Context checked':''}</span><code>${tm(x.time)}</code></div><div class="vr-issue-row"><span>Wrong</span><strong>${esc(x.found)}</strong></div><div class="vr-issue-row"><span>Correct</span><strong>${esc(x.fix)}</strong></div></article>`).join(''):`<div class="vr-empty"><strong>✓ No clear mistakes found.</strong><span>Logos, legal/registration lines, URLs, contact details, disclaimers and unstable OCR frames are filtered out.</span></div>`);if(issues.length)$('vr-copy-all').onclick=async()=>{const txt=issues.map(x=>`${tm(x.time)} — ${x.found} → ${x.fix}`).join('\n');try{await navigator.clipboard.writeText(txt)}catch{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}$('vr-copy-all').textContent='Copied ✓';setTimeout(()=>$('vr-copy-all').textContent='Copy all',1200)};st.textContent=`Review complete — ${issues.length} issue${issues.length===1?'':'s'} found.`}catch(e){st.textContent=e.message;box.innerHTML=`<div class="vr-empty">${esc(e.message)}</div>`}finally{if(S.scheduler){try{await S.scheduler.terminate()}catch{}S.scheduler=null}S.workers=[]}}
function setVideo(src,label){const v=$('vr-video');v.src=src;v.hidden=false;$('vr-start').disabled=true;$('vr-source-name').textContent=label;v.onloadedmetadata=()=>{$('vr-start').disabled=false;$('vr-status').textContent=`${label} loaded — ready to scan`};v.onerror=()=>{$('vr-start').disabled=true;$('vr-status').textContent=`Could not load ${label}. Check the share permissions.`}}
function drive(){const raw=$('vr-drive').value.trim();if(!raw)return;let u;try{u=new URL(raw)}catch{$('vr-status').textContent='Please paste a valid Google Drive link.';return}const m=u.pathname.match(/\/file\/d\/([\w-]+)/)||u.pathname.match(/\/d\/([\w-]+)/)||u.search.match(/[?&]id=([\w-]+)/);if(!m){$('vr-status').textContent='Could not find a Google Drive file ID in that link.';return}const id=m[1],rk=u.searchParams.get('resourcekey')||u.searchParams.get('resourceKey')||'';setVideo(`/api/drive-video?id=${encodeURIComponent(id)}${rk?'&resourcekey='+encodeURIComponent(rk):''}`,'Google Drive video')}
function frameio(){const raw=$('vr-frameio').value.trim();if(!raw)return;let u;try{u=new URL(raw)}catch{$('vr-status').textContent='Please paste a valid Frame.io link.';return}if(!/frame\.io$/i.test(u.hostname)&&!u.hostname.endsWith('.frame.io')){$('vr-status').textContent='Please paste a Frame.io share link.';return}setVideo(`/api/frameio-video?url=${encodeURIComponent(u.toString())}`,'Frame.io video')}
function init(){document.querySelectorAll('.vr-mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.vr-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.mode=b.dataset.mode});$('vr-file').onchange=()=>{const f=$('vr-file').files[0];if(!f)return;setVideo(URL.createObjectURL(f),f.name)};$('vr-drive').onchange=drive;$('vr-drive').onblur=drive;$('vr-frameio').onchange=frameio;$('vr-frameio').onblur=frameio;$('vr-script-text').oninput=scriptSetup;$('vr-start').onclick=scan;$('vr-cancel').onclick=()=>S.cancel=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();